spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring-in-action?characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: Lhm123456
#  sql:
#    init:
#      schema-locations:
#        - classpath:sql/schema.sql
#      mode: always
#      data-locations:
#        - classpath:sql/data.sql

logging:
  file:
      name: logs/info.log
  level:
    root: info
    org:
      springframework:
        security: DEBUG
    com.zaxxer.hikari: error

order:
  page-size: 20

